"
" General Settings
"

set encoding=utf-8

set tabstop=4  " how many columns a tab counts for
set expandtab  " tabs are spaces
set shiftwidth=4  " how many columns text is indented
set softtabstop=4  " number of columns when you hit tab in insert mode
set autoindent  " copy indent from current line when starting a new line

set backspace=indent,eol,start  " allow backspacing over everything

set wrap  " wrap long lines
set textwidth=79  " break long lines

set relativenumber  " show line numbers relative to current line

set showmatch  " highlight matching [{()}]

set incsearch  " search as characters are entered
set hlsearch  " highlight matches
set ignorecase  " ignore case in search patterns (...)
set smartcase   " if it contains lowercase letters only

" first complete longest common string and invoke wildmenu,
" then complete the first alternative and cycle throught the rest
set wildmenu
set wildmode=longest:full,full

set clipboard=unnamedplus  " use the system clipboard

set novisualbell  " no blinking
set noerrorbells  " no noise

if has('gui_running')
    set guifont=Ubuntu\ Mono\ 11
    set guioptions-=T  " remove toolbar
endif

"
" Keyboard Shortcuts
"

let mapleader='\'
noremap <Leader>l :set background=light<CR>
noremap <Leader>d :set background=dark<CR>

" move vertically by visual line (for wrapped lines)
nnoremap j gj
nnoremap k gk

" <Ctrl-l> redraws the screen and removes any search highlighting
nnoremap <silent> <C-l> :nohlsearch<CR><C-l>

"
" Vundle Plugins
"

set nocompatible
filetype off
set rtp+=~/.vim/vundle/Vundle.vim
call vundle#begin('~/.vim/vundle/')

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'gagoar/StripWhiteSpaces'
Plugin 'kien/ctrlp.vim'

call vundle#end()
filetype plugin indent on

" vim-colors-solarized
syntax enable
set t_Co=16
set background=dark
colorscheme solarized

" StripWhiteSpaces
let g:strip_trailing_lines = 1
