"
" General Settings
"

set encoding=utf-8

set tabstop=4  " how many columns a tab counts for
set expandtab  " tabs are spaces
set shiftwidth=4  " how many columns text is indented
set softtabstop=4  " number of columns when you hit tab in insert mode
set autoindent  " copy indent from current line when starting a new line

set backspace=indent,eol,start  " allow backspacing over everything

set wrap  " wrap long lines
set linebreak  " do not break words
set textwidth=79  " break long lines

set relativenumber  " show line numbers relative to current line

set showmatch  " highlight matching [{()}]

set incsearch  " search as characters are entered
set hlsearch  " highlight matches
set ignorecase  " ignore case in search patterns (...)
set smartcase   " if it contains lowercase letters only

" first complete longest common string and invoke wildmenu,
" then complete the first alternative and cycle throught the rest
set wildmenu
set wildmode=longest:full,full

set clipboard=unnamedplus  " use the system clipboard

set novisualbell  " no blinking
set noerrorbells  " no noise

if has('gui_running')
    set guifont=Ubuntu\ Mono\ 11
    set guioptions-=T  " remove toolbar
    set lines=42 columns=86  " set the window size
endif

"
" Keyboard Shortcuts
"

let mapleader='\'

" light/dark solarized color scheme
noremap <leader>l :set background=light<CR>
noremap <leader>d :set background=dark<CR>

noremap <leader>w :w!<cr>  " Fast saving

" move vertically by visual line (for wrapped lines)
nnoremap j gj
nnoremap k gk

" <Ctrl-l> redraws the screen and removes any search highlighting
nnoremap <silent> <C-l> :nohlsearch<CR><C-l>

"
" Specific File Type Settings
"
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmldjango setlocal shiftwidth=2 tabstop=2 softtabstop=2
let g:html_indent_inctags = "body,head"

"
" Vundle Plugins
"

set nocompatible
filetype off
set rtp+=~/.vim/vundle/Vundle.vim
call vundle#begin('~/.vim/vundle/')

Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'gagoar/StripWhiteSpaces'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

call vundle#end()
filetype plugin indent on

" vim-colors-solarized
syntax enable
set t_Co=16
set background=dark
colorscheme solarized

" StripWhiteSpaces
let g:strip_trailing_lines = 1

" NERDTree
map <silent> <C-n> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" vim-markdown
let g:vim_markdown_math=1
let g:vim_markdown_folding_disabled=1
