# ~/.zprofile: This file is similar to zlogin, but it is sourced before zshrc.

if [[ -z "$LANG" ]]; then
  export LANG='en_CA.UTF-8'
fi

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=($HOME $cdpath)

export TMPDIR="/tmp/$USER"
if [[ ! -d "$TMPDIR" ]]; then
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Configure editor, pager.
export EDITOR="vim"
export PAGER="less"
export LESS="-F -g -i -M -R -S -w -X -z-4"
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
