# ~/.zshrc: This file is sourced by interactive shells. It should define aliases,
# functions, shell options, and key bindings.

#
# Prezto
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# pyenv
#

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source "$HOME/.pyenv/completions/pyenv.zsh"
