# ~/.zshrc: This file is sourced by interactive shells. It should define aliases,
# functions, shell options, and key bindings.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && path=($PYENV_ROOT/bin $path)
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv init - zsh)"
eval "$(pyenv virtualenv-init -)"

# dircolors
eval `dircolors ~/.dircolors`
alias ls="ls --color=always"
