#+TITLE: Yasser Gonzalez's Emacs Configuration

* About

  This is my Emacs configuration maintained in an Org-mode file.
  The =/.emacs.d/init.el= file simply loads all the Elisp code in
  this document using Org-babel:

#+BEGIN_SRC emacs-lisp  :tangle no
  (require 'org)
  (setq vc-follow-symlinks nil)
  (defvar yasserglez/config-file "~/.emacs.d/config.org")
  (org-babel-load-file yasserglez/config-file)
#+END_SRC

  I use the following interactive functions to edit and reload this
  file within Emacs.

#+BEGIN_SRC emacs-lisp
  (defun yasserglez/edit-config-file ()
    (interactive)
    (find-file yasserglez/config-file))

  (defun yasserglez/reload-config-file ()
    (interactive)
    (org-babel-load-file yasserglez/config-file))
#+END_SRC

* Package Management

  I use Emacs' built-in =package.el= for package management with the
  GNU and MELPA Stable repos (and also other package-specific repos).
  =package-enable-at-startup= is set to nil, to avoid loading the
  packages again after processing the init file.

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-archives
        '(("gnu" . "http://elpa.gnu.org/packages/")
          ("melpa-stable" . "http://stable.melpa.org/packages/")
          ("elpy" . "http://jorgenschaefer.github.io/packages/")))
  (setq package-enable-at-startup nil)
  (package-initialize)
#+END_SRC

  I keep a list of packages that I use very often so they can be
  easily installed using the =yasserglez/install-base-packages=
  function on a new Emacs installation.

#+BEGIN_SRC emacs-lisp
  (defvar yasserglez/base-packages
    '(auctex elpy magit relative-line-numbers solarized-theme))

  (defun yasserglez/install-base-packages ()
    (interactive)
    (package-refresh-contents)
    (mapc (lambda (package)
            (unless (package-installed-p package)
              (package-install package)))
          yasserglez/base-packages))
#+END_SRC

  The following two functions are based on
  http://milkbox.net/note/single-file-master-emacs-configuration.
  =yasserglez/when-package-is-available= is used for code that should
  run if the package is available (when =package.el= installs a new
  package it creates an autoload file named as the package with
  =-autoloads= appended). =yasserglez/after-package-loaded= is used
  for code that should run after a package is loaded by checking for a
  feature name provided by the package.

#+BEGIN_SRC emacs-lisp
  (defmacro yasserglez/when-package-is-available (package &rest code)
    (declare (indent defun))
    `(eval-after-load ,(concat package "-autoloads")
       '(progn ,@code)))

  (defmacro yasserglez/after-package-is-loaded (package &rest code)
    (declare (indent defun))
    `(eval-after-load ,package
       '(progn ,@code)))
#+END_SRC

* Appearance

  Settings related with Emacs' appearance.

** Start on a maximized window

#+BEGIN_SRC emacs-lisp
     (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+END_SRC

** Show the buffer name in the window title

#+BEGIN_SRC emacs-lisp
  (setq frame-title-format "%b")
#+END_SRC

** Disable the menubar, the toolbar and the scrollbars

   Enable Unity global app menu integration for Emacs using
   =gsettings set com.canonical.unity-gtk-module whitelist "['emacs24']"=.

#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+END_SRC

** Solarized color theme

#+BEGIN_SRC emacs-lisp
  (yasserglez/when-package-is-available "solarized-theme"
    ;; Don't change the size of org-mode headlines
    (setq solarized-scale-org-headlines nil)
    ;; Avoid all font-size changes
    (setq solarized-height-minus-1 1.0)
    (setq solarized-height-plus-1 1.0)
    (setq solarized-height-plus-2 1.0)
    (setq solarized-height-plus-3 1.0)
    (setq solarized-height-plus-4 1.0)
    (load-theme 'solarized-dark t))
#+END_SRC

** Display relative line numbers

#+BEGIN_SRC emacs-lisp
  (yasserglez/when-package-is-available "relative-line-numbers"
    (global-relative-line-numbers-mode))
#+END_SRC

** Show line and column number in the mode line

#+BEGIN_SRC emacs-lisp
  (line-number-mode)
  (column-number-mode)
#+END_SRC

* Python

  I use Elpy for Python development. Jedi (=pip install --user jedi=)
  is required for code completion, and flake8
  (=pip install --user flake8=) for code checking.

#+BEGIN_SRC emacs-lisp
  (yasserglez/when-package-is-available "elpy"
    (elpy-enable)
    ;; Use Jedi for introspection and completion
    (setq elpy-rpc-backend "jedi")
    ;; Use IPython as the interactive intepreter
    (elpy-use-ipython)
    ;; Run tests using pytest
    (elpy-set-test-runner 'elpy-test-pytest-runner)
    ;; Disable highlight-indentation
    (setq elpy-modules (delq 'elpy-module-highlight-indentation elpy-modules)))
#+END_SRC

* LaTeX

  I use AUCTeX to write LaTeX documents.

#+BEGIN_SRC emacs-lisp
  (yasserglez/when-package-is-available "auctex"
    ;; Enable the PDF mode
    (setq TeX-PDF-mode t)
    ;; Enable document parsing
    (setq TeX-auto-save t)
    (setq TeX-parse-self t)
    ;; Make AUCTeX aware of multi-file documents
    (setq-default TeX-master nil))
#+END_SRC

* Git

  Git integration using Magit.

#+BEGIN_SRC emacs-lisp
  (yasserglez/when-package-is-available "magit"
    ;; vc-git no longer needed.
    (delete 'Git vc-handled-backends)
    ;; Don't show " MRev" in modeline.
    (setq magit-auto-revert-mode-lighter "")
    ;; Bind a global key to magit-status.
    (global-set-key (kbd "C-c g") 'magit-status))
#+END_SRC

* Miscellaneous

  Settings that don't fit in any previous category.

** Disable prompts and startup messages

   Based on http://www.masteringemacs.org/article/disabling-prompts-emacs.

#+BEGIN_SRC emacs-lisp
  ;; Ask "yes or no" questions with "y or n"
  (fset 'yes-or-no-p 'y-or-n-p)

  ;; Disable confirmations for non-existing files or buffers
  (setq confirm-nonexistent-file-or-buffer nil)

  ;; Disable the splash screen and the echo area message
  (setq inhibit-startup-message t
        inhibit-startup-echo-area-message "yasserglez")

  ;; Kill a buffer even if it has a process attached to it
  (setq kill-buffer-query-functions
    (remq 'process-kill-buffer-query-function
           kill-buffer-query-functions))
#+END_SRC

** Disable auto-save and backups

#+BEGIN_SRC emacs-lisp
  (setq auto-save-default nil)
  (setq make-backup-files nil)
#+END_SRC

** End sentences with one space

#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

** Remove trailing whitespace on save

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

** RET auto-indents by default

#+BEGIN_SRC emacs-lisp
  (define-key global-map (kbd "RET") 'newline-and-indent)
#+END_SRC
